Bump express-fileupload from 1.4.1 to 1.4.2 (#1276)
Bumps
[express-fileupload](https://github.com/richardgirges/express-fileupload)
from 1.4.1 to 1.4.2.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/richardgirges/express-fileupload/releases">express-fileupload's
releases</a>.</em></p>
<blockquote>
<h2>v1.4.2</h2>
<h2>What's Changed</h2>
<ul>
<li>Fix TypeError: file.destroy is not a function (issue <a
href="https://redirect.github.com/richardgirges/express-fileupload/issues/259">#259</a>).</li>
<li>Stricter request method and headers checks (to comply with RFC
2046).</li>
<li>Do not run next after abortion on limit (issue <a
href="https://redirect.github.com/richardgirges/express-fileupload/issues/238">#238</a>).</li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/richardgirges/express-fileupload/compare/v1.4.1...v.1.4.2">https://github.com/richardgirges/express-fileupload/compare/v1.4.1...v.1.4.2</a></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/richardgirges/express-fileupload/commit/fbee074bef0c0995aeb54575bdab0b2e2d9d4e72"><code>fbee074</code></a>
Merge pull request <a
href="https://redirect.github.com/richardgirges/express-fileupload/issues/363">#363</a>
from RomanBurunkov/master</li>
<li><a
href="https://github.com/richardgirges/express-fileupload/commit/fe62c7bbf30ec7b9498e0f4df625395926993f62"><code>fe62c7b</code></a>
Merge branch 'richardgirges:master' into master</li>
<li><a
href="https://github.com/richardgirges/express-fileupload/commit/254fc5542cd6140b096a7fd4c21e3f582e381481"><code>254fc55</code></a>
Bump ver to 1.4.2 &amp; update dependancies</li>
<li><a
href="https://github.com/richardgirges/express-fileupload/commit/24749bd5b5c03acd73b36775463ebca4c23a50b5"><code>24749bd</code></a>
Merge pull request <a
href="https://redirect.github.com/richardgirges/express-fileupload/issues/362">#362</a>
from RomanBurunkov/master</li>
<li><a
href="https://github.com/richardgirges/express-fileupload/commit/718a5747ca2baf4540250cee3219eb286d820d36"><code>718a574</code></a>
Do not run next after abortion on limit</li>
<li><a
href="https://github.com/richardgirges/express-fileupload/commit/fcb6952cfcdb7c5683a8910fe11aeb98eafc02d7"><code>fcb6952</code></a>
Merge pull request <a
href="https://redirect.github.com/richardgirges/express-fileupload/issues/359">#359</a>
from RomanBurunkov/master</li>
<li><a
href="https://github.com/richardgirges/express-fileupload/commit/9f4d71de3b8d662ec0766307601b212e5f3d2fea"><code>9f4d71d</code></a>
Add tests for isEligibleRequest</li>
<li><a
href="https://github.com/richardgirges/express-fileupload/commit/9f83dd385c57ea7169252a32b71b15d307462b35"><code>9f83dd3</code></a>
Stricter request method and headers checks</li>
<li><a
href="https://github.com/richardgirges/express-fileupload/commit/b3e48f0c249c7dd35f41825d4b75c58087003f92"><code>b3e48f0</code></a>
isAligibleRequest: Use set for unacceptable methods instead of array
&amp; some f...</li>
<li><a
href="https://github.com/richardgirges/express-fileupload/commit/64bbb9acfad2772ac404d127e00eeeafe533ce82"><code>64bbb9a</code></a>
Fix copyFile, moveFile, deleteFile tests</li>
<li>Additional commits viewable in <a
href="https://github.com/richardgirges/express-fileupload/compare/v1.4.1...v1.4.2">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=express-fileupload&package-manager=npm_and_yarn&previous-version=1.4.1&new-version=1.4.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>