Bump ansis from 3.12.0 to 3.14.0 (#2404)
Bumps [ansis](https://github.com/webdiscus/ansis) from 3.12.0 to 3.14.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/webdiscus/ansis/releases">ansis's
releases</a>.</em></p>
<blockquote>
<h1>v3.14.0</h1>
<h1>Cumulative Release v3.6.0 - v3.14.0</h1>
<h2>Features</h2>
<ul>
<li>
<p>Added support for chromium-based browsers.<br />
Now you can use truecolor in the consoles of Chrome, Edge, Opera, Brave,
Vivaldi and other Chromium-based browsers.
Browsers that do not support ANSI codes will display black and white
text.</p>
</li>
<li>
<p>Added support for <code>\n</code> as a newline in template literals,
e.g.: <code>green`Hello\nWorld`</code> renders:</p>
<pre><code>Hello
World
</code></pre>
</li>
<li>
<p>Function <code>ansis.reset()</code> returns the reset escape code
<code>\e[0m</code>.</p>
</li>
<li>
<p>Enforce a specific color support by a <code>FORCE_COLOR</code>
value:</p>
<ul>
<li>false - Disables colors</li>
<li>0 - Disables colors</li>
<li>true (or unset) - Auto detects the supported colors (if no color
detected, enforce truecolor)</li>
<li>1 - Enables 16 colors</li>
<li>2 - Enables 256 colors</li>
<li>3 - Enables truecolor</li>
</ul>
</li>
<li>
<p>Removed <strong>undocumented</strong> pointless dummy function
<code>ansis(any)</code>.</p>
</li>
</ul>
<blockquote>
<p>[!WARNING]
This is not a BREAKING CHANGE because it was never officially
documented!</p>
<pre lang="js"><code>import ansis from 'ansis';
ansis('text'); // &lt;= now will occur the ERROR TS2349: This expression
is not callable.
</code></pre>
<p>This warning applies only to projects where Chalk was replaced with
Ansis and something like <code>chalk('text')</code> was used.</p>
<p>Just replace <code>ansis('text')</code> with <code>'text'</code>.</p>
<p>The <code>ansis('text')</code> function was a dummy and did nothing
except return the same input string.</p>
</blockquote>
<ul>
<li>Added support for legacy Node.js v14 (in package.json for npm was
changed the <code>engines</code> to <code>&quot;node&quot;:
&quot;&gt;=14&quot;</code>).</li>
<li>Micro optimisations for slight performance improvements.</li>
</ul>
<h2>Bug Fixes</h2>
<ul>
<li>If the function argument is an empty string should be returned an
empty string w/o escape codes:
<pre lang="js"><code>ansis.red('') =&gt; '', // returns empty string w/o
escape codes
</code></pre>
</li>
<li>Cast falsy values <code>false</code> and <code>NaN</code> to a
string.
In previous versions, the empty string <code>''</code> was returned for
falsy values.</li>
<li>Functions with argument <code>0</code> , e.g.
<code>ansis.red(0)</code>, returning empty string <code>''</code>, now
return colored value <code>'0'</code></li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/webdiscus/ansis/blob/master/CHANGELOG.md">ansis's
changelog</a>.</em></p>
<blockquote>
<h2>3.14.0 (2025-02-13)</h2>
<ul>
<li>feat: add support for chromium-based browsers.<br />
Now you can use truecolor in the consoles of Chrome, Edge, Brave, and
other Chromium-based browsers.
Browsers that do not support ANSI codes will display black and white
text.</li>
<li>refactor: slight reduce the package size by ~40 bytes</li>
</ul>
<h2>3.13.0 (2025-02-13)</h2>
<p>Skip this version number.</p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/webdiscus/ansis/commits/v3.14.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=ansis&package-manager=npm_and_yarn&previous-version=3.12.0&new-version=3.14.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>